# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.AddFieldsData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :fields
  ]

  @type t :: %__MODULE__{
    :fields => [map()]
  }

  def decode(value) do
    value
  end
end

