# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.AddFieldsData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"fields"
  ]

  @type t :: %__MODULE__{
    :"fields" => [TemplatestemplateIdaddFieldsFields]
  }
end

defimpl Poison.Decoder, for: Docspring.Model.AddFieldsData do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"fields", :list, Docspring.Model.TemplatestemplateIdaddFieldsFields, options)
  end
end

