# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CombinedSubmission do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"metadata",
    :"password",
    :"expired",
    :"expires_at",
    :"source_pdfs",
    :"pdf_hash",
    :"download_url",
    :"submission_ids",
    :"id",
    :"state",
    :"actions"
  ]

  @type t :: %__MODULE__{
    :"metadata" => Object,
    :"password" => String.t,
    :"expired" => boolean(),
    :"expires_at" => String.t,
    :"source_pdfs" => [Object],
    :"pdf_hash" => String.t,
    :"download_url" => String.t,
    :"submission_ids" => [String.t],
    :"id" => String.t,
    :"state" => String.t,
    :"actions" => [CombinedSubmissionAction]
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CombinedSubmission do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metadata", :struct, Docspring.Model.Object, options)
    |> deserialize(:"source_pdfs", :list, Docspring.Model.Object, options)
    |> deserialize(:"actions", :list, Docspring.Model.CombinedSubmissionAction, options)
  end
end

