# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CombinePdfsData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"delete_custom_files",
    :"expires_in",
    :"metadata",
    :"password",
    :"source_pdfs",
    :"test"
  ]

  @type t :: %__MODULE__{
    :"delete_custom_files" => boolean(),
    :"expires_in" => integer(),
    :"metadata" => Object,
    :"password" => String.t,
    :"source_pdfs" => [Object],
    :"test" => boolean()
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CombinePdfsData do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metadata", :struct, Docspring.Model.Object, options)
    |> deserialize(:"source_pdfs", :list, Docspring.Model.Object, options)
  end
end

