# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CombinedSubmissionAction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"integration_id",
    :"state",
    :"action_category",
    :"action_type",
    :"result_data"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"integration_id" => String.t,
    :"state" => String.t,
    :"action_category" => String.t,
    :"action_type" => String.t,
    :"result_data" => Object
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CombinedSubmissionAction do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"result_data", :struct, Docspring.Model.Object, options)
  end
end

