# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CombinedSubmissionData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :expires_in,
    :metadata,
    :password,
    :submission_ids,
    :test
  ]

  @type t :: %__MODULE__{
    :expires_in => integer() | nil,
    :metadata => map() | nil,
    :password => String.t | nil,
    :submission_ids => [String.t],
    :test => boolean() | nil
  }

  def decode(value) do
    value
  end
end

