# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CombinedSubmission do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :state,
    :expired,
    :expires_in,
    :expires_at,
    :processed_at,
    :error_message,
    :submission_ids,
    :source_pdfs,
    :metadata,
    :password,
    :pdf_hash,
    :download_url,
    :actions
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :state => String.t,
    :expired => boolean(),
    :expires_in => integer() | nil,
    :expires_at => String.t | nil,
    :processed_at => String.t | nil,
    :error_message => String.t | nil,
    :submission_ids => [String.t],
    :source_pdfs => [map()],
    :metadata => map(),
    :password => String.t | nil,
    :pdf_hash => String.t | nil,
    :download_url => String.t | nil,
    :actions => [Docspring.Model.CombinedSubmissionAction.t]
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:actions, :list, Docspring.Model.CombinedSubmissionAction)
  end
end

