# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CombinedSubmissionAction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :integration_id,
    :state,
    :action_type,
    :action_category,
    :result_data
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :integration_id => String.t | nil,
    :state => String.t,
    :action_type => String.t,
    :action_category => String.t,
    :result_data => map()
  }

  def decode(value) do
    value
  end
end

