# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CombinedSubmissionData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"expires_in",
    :"metadata",
    :"password",
    :"submission_ids",
    :"test"
  ]

  @type t :: %__MODULE__{
    :"expires_in" => integer(),
    :"metadata" => Object,
    :"password" => String.t,
    :"submission_ids" => [String.t],
    :"test" => boolean()
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CombinedSubmissionData do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metadata", :struct, Docspring.Model.Object, options)
  end
end

