# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CombinePdfsData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :delete_custom_files,
    :expires_in,
    :metadata,
    :password,
    :source_pdfs,
    :test
  ]

  @type t :: %__MODULE__{
    :delete_custom_files => boolean() | nil,
    :expires_in => integer() | nil,
    :metadata => map() | nil,
    :password => String.t | nil,
    :source_pdfs => [map()],
    :test => boolean() | nil
  }

  def decode(value) do
    value
  end
end

