# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CreateCustomFileResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :errors,
    :custom_file
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :errors => [String.t] | nil,
    :custom_file => map()
  }

  def decode(value) do
    value
  end
end

