# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CreateSubmissionResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :errors,
    :submission
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :errors => [String.t] | nil,
    :submission => Docspring.Model.Submission.t
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:submission, :struct, Docspring.Model.Submission)
  end
end

