# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CreateCombinedSubmissionResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"combined_submission",
    :"errors",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"combined_submission" => CombinedSubmission,
    :"errors" => [String.t],
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CreateCombinedSubmissionResponse do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"combined_submission", :struct, Docspring.Model.CombinedSubmission, options)
  end
end

