# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CreateHtmlTemplateData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"template"
  ]

  @type t :: %__MODULE__{
    :"template" => HtmlTemplateData
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CreateHtmlTemplateData do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"template", :struct, Docspring.Model.HtmlTemplateData, options)
  end
end

