# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CreateSubmissionResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :submission,
    :errors
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :submission => Docspring.Model.SubmissionPreview.t,
    :errors => [String.t] | nil
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:submission, :struct, Docspring.Model.SubmissionPreview)
  end
end

