# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CreateSubmissionBatchResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"submission_batch",
    :"submissions",
    :"error",
    :"errors",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"submission_batch" => SubmissionBatch,
    :"submissions" => [CreateSubmissionBatchSubmissionsResponse],
    :"error" => String.t,
    :"errors" => [String.t],
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CreateSubmissionBatchResponse do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"submission_batch", :struct, Docspring.Model.SubmissionBatch, options)
    |> deserialize(:"submissions", :list, Docspring.Model.CreateSubmissionBatchSubmissionsResponse, options)
  end
end

