# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CreateTemplateFromUploadData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :template
  ]

  @type t :: %__MODULE__{
    :template => Docspring.Model.UploadTemplateData.t
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:template, :struct, Docspring.Model.UploadTemplateData)
  end
end

