# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CreateCustomFileResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :custom_file,
    :errors
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :custom_file => Docspring.Model.CustomFile.t,
    :errors => [String.t] | nil
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:custom_file, :struct, Docspring.Model.CustomFile)
  end
end

