# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CreateHtmlSubmissionData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :css,
    :data,
    :editable,
    :expires_in,
    :field_overrides,
    :html,
    :metadata,
    :password,
    :test
  ]

  @type t :: %__MODULE__{
    :css => String.t | nil,
    :data => map() | nil,
    :editable => boolean() | nil,
    :expires_in => integer() | nil,
    :field_overrides => map() | nil,
    :html => String.t | nil,
    :metadata => map() | nil,
    :password => String.t | nil,
    :test => boolean() | nil
  }

  def decode(value) do
    value
  end
end

