# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CreateFolderData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"folder"
  ]

  @type t :: %__MODULE__{
    :"folder" => FoldersFolder
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CreateFolderData do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"folder", :struct, Docspring.Model.FoldersFolder, options)
  end
end

