# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CreateSubmissionResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"submission",
    :"errors",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"submission" => Submission,
    :"errors" => [String.t],
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CreateSubmissionResponse do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"submission", :struct, Docspring.Model.Submission, options)
  end
end

