# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CreateCustomFileResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"custom_file",
    :"errors",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"custom_file" => CustomFile,
    :"errors" => [String.t],
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CreateCustomFileResponse do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"custom_file", :struct, Docspring.Model.CustomFile, options)
  end
end

