# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.CreateCustomFileData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cache_id"
  ]

  @type t :: %__MODULE__{
    :"cache_id" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.CreateCustomFileData do
  def decode(value, _options) do
    value
  end
end

