# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CreateSubmissionDataRequestData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :auth_second_factor_type,
    :auth_type,
    :fields,
    :metadata,
    :order
  ]

  @type t :: %__MODULE__{
    :auth_second_factor_type => String.t | nil,
    :auth_type => String.t | nil,
    :fields => [String.t] | nil,
    :metadata => map() | nil,
    :order => integer() | nil
  }

  def decode(value) do
    value
  end
end

