# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.CustomFile do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :url
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :url => String.t | nil
  }

  def decode(value) do
    value
  end
end

