# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.Error do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"error"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t,
    :"error" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.Error do
  def decode(value, _options) do
    value
  end
end

