# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.FullTemplate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :description,
    :public_web_form,
    :public_submissions,
    :expire_submissions,
    :expire_after,
    :expiration_interval,
    :allow_additional_properties,
    :editable_submissions,
    :locked,
    :webhook_url,
    :slack_webhook_url,
    :redirect_url,
    :first_template,
    :html,
    :header_html,
    :footer_html,
    :scss,
    :encrypt_pdfs,
    :encrypt_pdfs_password,
    :defaults,
    :fields,
    :shared_field_data,
    :field_order,
    :document_md5,
    :document_filename,
    :document_parse_error,
    :document_state,
    :embed_domains,
    :page_count,
    :document_processed,
    :demo,
    :id,
    :template_type,
    :page_dimensions,
    :document_url,
    :permanent_document_url,
    :path,
    :parent_folder_id
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :description => String.t | nil,
    :public_web_form => boolean(),
    :public_submissions => boolean(),
    :expire_submissions => boolean(),
    :expire_after => float(),
    :expiration_interval => String.t,
    :allow_additional_properties => boolean(),
    :editable_submissions => boolean(),
    :locked => boolean(),
    :webhook_url => String.t | nil,
    :slack_webhook_url => String.t | nil,
    :redirect_url => String.t | nil,
    :first_template => boolean(),
    :html => String.t | nil,
    :header_html => String.t | nil,
    :footer_html => String.t | nil,
    :scss => String.t | nil,
    :encrypt_pdfs => boolean(),
    :encrypt_pdfs_password => String.t | nil,
    :defaults => Docspring.Model.TemplateDefaults.t,
    :fields => map(),
    :shared_field_data => map(),
    :field_order => [[float()]],
    :document_md5 => String.t | nil,
    :document_filename => String.t | nil,
    :document_parse_error => boolean(),
    :document_state => String.t,
    :embed_domains => [String.t] | nil,
    :page_count => float(),
    :document_processed => boolean(),
    :demo => boolean(),
    :id => String.t,
    :template_type => String.t,
    :page_dimensions => [[float()]] | nil,
    :document_url => String.t | nil,
    :permanent_document_url => String.t | nil,
    :path => String.t,
    :parent_folder_id => String.t | nil
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:defaults, :struct, Docspring.Model.TemplateDefaults)
  end
end

