# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.FullTemplateDefaults do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"color",
    :"fontSize",
    :"typeface"
  ]

  @type t :: %__MODULE__{
    :"color" => String.t,
    :"fontSize" => float(),
    :"typeface" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.FullTemplateDefaults do
  def decode(value, _options) do
    value
  end
end

