# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.HtmlTemplateDataWebhookOptions do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :exclude_data
  ]

  @type t :: %__MODULE__{
    :exclude_data => boolean() | nil
  }

  def decode(value) do
    value
  end
end

