# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.InvalidRequestSingleError do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :error
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :error => String.t
  }

  def decode(value) do
    value
  end
end

