# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.ListSubmissionsResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :submissions,
    :limit,
    :next_cursor
  ]

  @type t :: %__MODULE__{
    :submissions => [Docspring.Model.Submission.t],
    :limit => float(),
    :next_cursor => String.t | nil
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:submissions, :list, Docspring.Model.Submission)
  end
end

