# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.MoveTemplateData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"parent_folder_id"
  ]

  @type t :: %__MODULE__{
    :"parent_folder_id" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.MoveTemplateData do
  def decode(value, _options) do
    value
  end
end

