# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.MoveFolderData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :parent_folder_id
  ]

  @type t :: %__MODULE__{
    :parent_folder_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

