# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.PendingTemplate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"expiration_interval",
    :"webhook_url",
    :"parent_folder_id",
    :"expire_after",
    :"allow_additional_properties",
    :"description",
    :"public_submissions",
    :"slack_webhook_url",
    :"path",
    :"public_web_form",
    :"editable_submissions",
    :"expire_submissions",
    :"name",
    :"template_type",
    :"id",
    :"locked",
    :"redirect_url"
  ]

  @type t :: %__MODULE__{
    :"expiration_interval" => String.t,
    :"webhook_url" => String.t,
    :"parent_folder_id" => String.t,
    :"expire_after" => float(),
    :"allow_additional_properties" => boolean(),
    :"description" => String.t,
    :"public_submissions" => boolean(),
    :"slack_webhook_url" => String.t,
    :"path" => String.t,
    :"public_web_form" => boolean(),
    :"editable_submissions" => boolean(),
    :"expire_submissions" => boolean(),
    :"name" => String.t,
    :"template_type" => String.t,
    :"id" => String.t,
    :"locked" => boolean(),
    :"redirect_url" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.PendingTemplate do
  def decode(value, _options) do
    value
  end
end

