# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.PublishTemplateVersionResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :result
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :result => Docspring.Model.PublishTemplateVersionResponseResult.t
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:result, :struct, Docspring.Model.PublishTemplateVersionResponseResult)
  end
end

