# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.PublishVersionData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :version_type
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :version_type => String.t
  }

  def decode(value) do
    value
  end
end

