# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.RenameFolderData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name
  ]

  @type t :: %__MODULE__{
    :name => String.t
  }

  def decode(value) do
    value
  end
end

