# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.SubmissionBatch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"pending_count",
    :"completion_percentage",
    :"metadata",
    :"total_count",
    :"submissions",
    :"processed_at",
    :"id",
    :"state",
    :"error_count"
  ]

  @type t :: %__MODULE__{
    :"pending_count" => integer(),
    :"completion_percentage" => integer(),
    :"metadata" => Object,
    :"total_count" => integer(),
    :"submissions" => [Submission],
    :"processed_at" => String.t,
    :"id" => String.t,
    :"state" => String.t,
    :"error_count" => integer()
  }
end

defimpl Poison.Decoder, for: Docspring.Model.SubmissionBatch do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metadata", :struct, Docspring.Model.Object, options)
    |> deserialize(:"submissions", :list, Docspring.Model.Submission, options)
  end
end

