# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.SubmissionBatchWithSubmissions do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :state,
    :metadata,
    :processed_at,
    :total_count,
    :pending_count,
    :error_count,
    :completion_percentage,
    :submissions
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :state => String.t,
    :metadata => map(),
    :processed_at => String.t | nil,
    :total_count => integer(),
    :pending_count => integer(),
    :error_count => integer(),
    :completion_percentage => float(),
    :submissions => [Docspring.Model.SubmissionPreview.t] | nil
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:submissions, :list, Docspring.Model.SubmissionPreview)
  end
end

