# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.SubmissionDataRequestToken do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :secret,
    :expires_at,
    :data_request_url
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :secret => String.t,
    :expires_at => String.t | nil,
    :data_request_url => String.t | nil
  }

  def decode(value) do
    value
  end
end

