# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.SubmissionData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :css,
    :data,
    :data_requests,
    :html,
    :metadata,
    :test
  ]

  @type t :: %__MODULE__{
    :css => String.t | nil,
    :data => map(),
    :data_requests => [Docspring.Model.CreateSubmissionDataRequestData.t] | nil,
    :html => String.t | nil,
    :metadata => map() | nil,
    :test => boolean() | nil
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data_requests, :list, Docspring.Model.CreateSubmissionDataRequestData)
  end
end

