# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.SubmissionBatchData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :metadata,
    :submissions,
    :template_id,
    :template_version,
    :test
  ]

  @type t :: %__MODULE__{
    :metadata => map() | nil,
    :submissions => [Docspring.Model.SubmissionDataBatchRequest.t],
    :template_id => String.t | nil,
    :template_version => String.t | nil,
    :test => boolean() | nil
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:submissions, :list, Docspring.Model.SubmissionDataBatchRequest)
  end
end

