# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.SubmissionPreview do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :batch_id,
    :data_requests,
    :editable,
    :expired,
    :expires_at,
    :id,
    :json_schema_errors,
    :metadata,
    :password,
    :processed_at,
    :state,
    :template_id,
    :template_type,
    :template_version,
    :test,
    :truncated_text,
    :pdf_hash,
    :download_url,
    :permanent_download_url,
    :preview_download_url,
    :preview_generated_at,
    :audit_trail_download_url,
    :actions
  ]

  @type t :: %__MODULE__{
    :batch_id => String.t | nil,
    :data_requests => [Docspring.Model.SubmissionDataRequest.t],
    :editable => boolean() | nil,
    :expired => boolean(),
    :expires_at => String.t | nil,
    :id => String.t | nil,
    :json_schema_errors => [String.t] | nil,
    :metadata => map(),
    :password => String.t | nil,
    :processed_at => String.t | nil,
    :state => String.t,
    :template_id => String.t | nil,
    :template_type => String.t,
    :template_version => String.t | nil,
    :test => boolean(),
    :truncated_text => map() | nil,
    :pdf_hash => String.t | nil,
    :download_url => String.t | nil,
    :permanent_download_url => String.t | nil,
    :preview_download_url => String.t | nil,
    :preview_generated_at => String.t | nil,
    :audit_trail_download_url => String.t | nil,
    :actions => [Docspring.Model.SubmissionAction.t]
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data_requests, :list, Docspring.Model.SubmissionDataRequest)
     |> Deserializer.deserialize(:actions, :list, Docspring.Model.SubmissionAction)
  end
end

