# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.SubmissionData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"css",
    :"data",
    :"data_requests",
    :"expires_in",
    :"field_overrides",
    :"html",
    :"metadata",
    :"password",
    :"test"
  ]

  @type t :: %__MODULE__{
    :"css" => String.t,
    :"data" => Object,
    :"data_requests" => [CreateSubmissionDataRequestData],
    :"expires_in" => integer(),
    :"field_overrides" => Object,
    :"html" => String.t,
    :"metadata" => Object,
    :"password" => String.t,
    :"test" => boolean()
  }
end

defimpl Poison.Decoder, for: Docspring.Model.SubmissionData do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :struct, Docspring.Model.Object, options)
    |> deserialize(:"data_requests", :list, Docspring.Model.CreateSubmissionDataRequestData, options)
    |> deserialize(:"field_overrides", :struct, Docspring.Model.Object, options)
    |> deserialize(:"metadata", :struct, Docspring.Model.Object, options)
  end
end

