# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.SubmissionBatchData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"metadata",
    :"submissions",
    :"template_id",
    :"test"
  ]

  @type t :: %__MODULE__{
    :"metadata" => Object,
    :"submissions" => [SubmissionDataBatchRequest],
    :"template_id" => String.t,
    :"test" => boolean()
  }
end

defimpl Poison.Decoder, for: Docspring.Model.SubmissionBatchData do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metadata", :struct, Docspring.Model.Object, options)
    |> deserialize(:"submissions", :list, Docspring.Model.SubmissionDataBatchRequest, options)
  end
end

