# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.SubmissionDataBatchRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :css,
    :data,
    :html,
    :metadata,
    :template_id,
    :template_version,
    :test
  ]

  @type t :: %__MODULE__{
    :css => String.t | nil,
    :data => map(),
    :html => String.t | nil,
    :metadata => map() | nil,
    :template_id => String.t | nil,
    :template_version => String.t | nil,
    :test => boolean() | nil
  }

  def decode(value) do
    value
  end
end

