# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.SubmissionBatchData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :metadata,
    :submissions,
    :test
  ]

  @type t :: %__MODULE__{
    :metadata => map() | nil,
    :submissions => [map()],
    :test => boolean() | nil
  }

  def decode(value) do
    value
  end
end

