# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.SubmissionDataRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"submission_id",
    :"name",
    :"email",
    :"order",
    :"sort_order",
    :"fields",
    :"metadata",
    :"state",
    :"viewed_at",
    :"completed_at",
    :"auth_type",
    :"auth_second_factor_type",
    :"auth_provider",
    :"auth_session_started_at",
    :"auth_session_id_hash",
    :"auth_user_id_hash",
    :"auth_username_hash",
    :"auth_phone_number_hash",
    :"ip_address",
    :"user_agent"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"submission_id" => String.t,
    :"name" => String.t,
    :"email" => String.t,
    :"order" => integer(),
    :"sort_order" => integer(),
    :"fields" => [String.t],
    :"metadata" => Object,
    :"state" => String.t,
    :"viewed_at" => String.t,
    :"completed_at" => String.t,
    :"auth_type" => String.t,
    :"auth_second_factor_type" => String.t,
    :"auth_provider" => String.t,
    :"auth_session_started_at" => String.t,
    :"auth_session_id_hash" => String.t,
    :"auth_user_id_hash" => String.t,
    :"auth_username_hash" => String.t,
    :"auth_phone_number_hash" => String.t,
    :"ip_address" => String.t,
    :"user_agent" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.SubmissionDataRequest do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metadata", :struct, Docspring.Model.Object, options)
  end
end

