# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.SubmissionDataBatchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"css",
    :"metadata",
    :"data",
    :"test",
    :"html",
    :"template_id"
  ]

  @type t :: %__MODULE__{
    :"css" => String.t,
    :"metadata" => Object,
    :"data" => Object,
    :"test" => boolean(),
    :"html" => String.t,
    :"template_id" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.SubmissionDataBatchRequest do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metadata", :struct, Docspring.Model.Object, options)
    |> deserialize(:"data", :struct, Docspring.Model.Object, options)
  end
end

