# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.Submission do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :template_id,
    :test,
    :editable,
    :expired,
    :expires_at,
    :processed_at,
    :state,
    :data,
    :metadata,
    :truncated_text,
    :pdf_hash,
    :download_url,
    :permanent_download_url,
    :batch_id,
    :data_requests,
    :actions,
    :source,
    :referrer
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :template_id => String.t | nil,
    :test => boolean(),
    :editable => boolean() | nil,
    :expired => boolean(),
    :expires_at => String.t | nil,
    :processed_at => String.t | nil,
    :state => String.t,
    :data => map() | nil,
    :metadata => map() | nil,
    :truncated_text => map() | nil,
    :pdf_hash => String.t | nil,
    :download_url => String.t | nil,
    :permanent_download_url => String.t | nil,
    :batch_id => String.t | nil,
    :data_requests => [Docspring.Model.SubmissionDataRequest.t] | nil,
    :actions => [Docspring.Model.SubmissionAction.t] | nil,
    :source => String.t | nil,
    :referrer => String.t | nil
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data_requests, :list, Docspring.Model.SubmissionDataRequest)
     |> Deserializer.deserialize(:actions, :list, Docspring.Model.SubmissionAction)
  end
end

