# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.TemplateDefaults do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :color,
    :fontSize,
    :typeface
  ]

  @type t :: %__MODULE__{
    :color => String.t | nil,
    :fontSize => float(),
    :typeface => String.t
  }

  def decode(value) do
    value
  end
end

