# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.TemplatePublishVersionResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :result,
    :errors
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :result => map(),
    :errors => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

