# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.TemplateDocumentMetadata do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :filename,
    :mime_type,
    :size
  ]

  @type t :: %__MODULE__{
    :filename => String.t,
    :mime_type => String.t,
    :size => integer()
  }

  def decode(value) do
    value
  end
end

