# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.UpdateDataRequestResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data_request",
    :"errors",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"data_request" => SubmissionDataRequest,
    :"errors" => [String.t],
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.UpdateDataRequestResponse do
  import Docspring.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data_request", :struct, Docspring.Model.SubmissionDataRequest, options)
  end
end

