# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.UpdateDataRequestResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :errors,
    :data_request
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :errors => [String.t] | nil,
    :data_request => Docspring.Model.SubmissionDataRequest.t
  }

  alias Docspring.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data_request, :struct, Docspring.Model.SubmissionDataRequest)
  end
end

