# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Docspring.Model.UploadPresign do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :fields,
    :headers,
    :url,
    :method
  ]

  @type t :: %__MODULE__{
    :fields => map(),
    :headers => map(),
    :url => String.t,
    :method => String.t | nil
  }

  def decode(value) do
    value
  end
end

