# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Docspring.Model.UploadTemplateDataDocumentMetadata do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"filename",
    :"size",
    :"mime_type"
  ]

  @type t :: %__MODULE__{
    :"filename" => String.t,
    :"size" => integer(),
    :"mime_type" => String.t
  }
end

defimpl Poison.Decoder, for: Docspring.Model.UploadTemplateDataDocumentMetadata do
  def decode(value, _options) do
    value
  end
end

